spring.application.name=TripNest_Backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/tripnest
spring.datasource.username=root
spring.datasource.password=Kishore4574

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=TripNestSuperSecretKeyForJwtAuthentication2026TripNest
jwt.expiration=86400000