spring.application.name=TripNest_Backend

spring.config.import=optional:application-secrets.properties

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/tripnest
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.expiration=86400000

gemini.model=gemini-3.6-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models

http.client.connect-timeout=10000
http.client.read-timeout=30000