version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: tripnest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 110806
      MYSQL_DATABASE: tn_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: tripnest-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tn_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 110806
    depends_on:
      - mysqldb

volumes:
  mysql-data:
