spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tripnest}
spring.datasource.username=${DB_USERNAME:tripnest}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
