import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Check, Heart, UserRound } from "lucide-react";
import api from "../services/api";

const preferenceOptions = ["Solo travel", "Family trips", "Food", "Nature", "Culture", "Adventure", "Slow travel"];

export default function Profile() {
  const [profile, setProfile] = useState(null); const [favorites, setFavorites] = useState([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { const [profileResponse, favoriteResponse] = await Promise.all([api.get("/profile"), api.get("/profile/favorites")]); setProfile(profileResponse.data); setFavorites(favoriteResponse.data); } catch { setError("Could not load your profile."); } };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); try { const { data } = await api.put("/profile", profile); setProfile(data); setMessage("Profile saved."); setTimeout(() => setMessage(""), 2500); } catch (requestError) { setError(requestError.response?.data?.message || "Could not save profile."); } };
  const togglePreference = (preference) => setProfile((value) => ({ ...value, travelPreferences: value.travelPreferences.includes(preference) ? value.travelPreferences.filter((item) => item !== preference) : [...value.travelPreferences, preference] }));
  if (!profile) return <main className="workspace-page">Loading your profile...</main>;
  return <main className="workspace-page"><Link className="back-link" to="/dashboard"><ArrowLeft size={16}/> Dashboard</Link><header className="workspace-heading"><p className="eyebrow">Personal travel profile</p><h1>Make TripNest yours.</h1><p>Save the details and travel preferences that make every plan feel personal.</p></header><section className="profile-grid"><form className="trip-form profile-form" onSubmit={save}><h2><UserRound size={18}/> Your profile</h2>{error && <p className="form-error">{error}</p>}{message && <p className="auth-success">{message}</p>}<label>Full name<input required value={profile.fullName} onChange={(event) => setProfile({ ...profile, fullName: event.target.value })}/></label><label>Email address<input value={profile.email} disabled/></label><label>Phone number<input required value={profile.phoneNumber} onChange={(event) => setProfile({ ...profile, phoneNumber: event.target.value })}/></label><label>Profile image URL<input value={profile.profileImageUrl || ""} onChange={(event) => setProfile({ ...profile, profileImageUrl: event.target.value })} placeholder="https://..."/></label><label>About your travel style<textarea value={profile.bio || ""} onChange={(event) => setProfile({ ...profile, bio: event.target.value })} placeholder="The kind of journeys you love..."/></label><div><p className="form-label">Travel preferences</p><div className="preference-chips">{preferenceOptions.map((preference) => <button type="button" className={profile.travelPreferences.includes(preference) ? "is-selected" : ""} onClick={() => togglePreference(preference)} key={preference}>{profile.travelPreferences.includes(preference) && <Check size={13}/>} {preference}</button>)}</div></div><button className="primary-button">Save changes</button></form><section className="trip-list profile-favorites"><div className="list-title"><h2><Heart size={18}/> Favorite destinations</h2><span>{favorites.length}</span></div>{favorites.length ? favorites.map((destination) => <Link className="trip-row" to={`/destinations/${destination.id}`} key={destination.id}><span className="trip-row__icon"><Heart size={18}/></span><span><strong>{destination.name}</strong><small>{[destination.city, destination.country].filter(Boolean).join(", ")}</small></span></Link>) : <div className="empty-state"><Heart size={28}/><h3>Save places you love</h3><p>Bookmark destinations from Discover to keep them close.</p></div>}</section></section></main>;
}
