# PostgreSQL Profile Configuration (Database: tn_web on port 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/tn_web
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=110806
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
