-- TripNest Comprehensive Indian States & World Destinations Seed Script

INSERT INTO destinations (destination_name, city, state, country, description, attractions, weather_info, travel_guide) VALUES 
('Tirumala Venkateswara Temple', 'Tirupati', 'Andhra Pradesh', 'India', 'Sri Venkateswara Swamy Temple on Tirumala Hills is one of the world''s most sacred pilgrimage destinations.', 'Tirumala Temple, Talakona Waterfalls, Chandragiri Fort', 'Hilltop climate (16°C-27°C).', 'Best Time: Sep-Mar | Entry: Free / ₹300 | Rating: 4.9'),
('Amaravati Stupa & Dhyana Buddha', 'Amaravati', 'Andhra Pradesh', 'India', 'Sacred Buddhist center along the Krishna River featuring a 125-foot Dhyana Buddha Statue and Satavahana ruins.', '125ft Dhyana Buddha, Maha Chaitya, ASI Museum', 'River valley climate.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.8'),
('RK Beach & Submarine Museum', 'Visakhapatnam', 'Andhra Pradesh', 'India', 'Visakhapatnam''s premier urban coastline promenade featuring INS Kursura Submarine Museum.', 'INS Kursura, TU-142 Aircraft Museum, Kali Temple', 'Tropical beach climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Araku Valley', 'Araku Valley', 'Andhra Pradesh', 'India', 'Scenic hill station in Eastern Ghats known for organic coffee plantations and mist.', 'Coffee Estates, Chaparai Cascades, Tribal Museum', 'Misty hill climate.', 'Best Time: Sep-Mar | Entry: Free | Rating: 4.8'),
('Borra Caves', 'Araku Valley', 'Andhra Pradesh', 'India', 'Million-year-old natural limestone caves reaching depths of 80 meters.', 'Stalactites, Gosthani River Gorge, Caverns', 'Cool cave environment.', 'Best Time: Oct-Mar | Entry: ₹80 | Rating: 4.7'),
('Gandikota Fort & Gorge', 'Gandikota', 'Andhra Pradesh', 'India', 'Grand Canyon of India featuring a 300-foot red sandstone gorge carved by Pennar River.', 'Pennar Gorge, Fort Ramparts, Jamia Masjid', 'Cool winter evenings.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Belum Caves', 'Kurnool', 'Andhra Pradesh', 'India', 'Second largest cave system in Indian subcontinent with underground streams.', 'Patalaganga, Dhyan Hall, Kotilingalu', 'Cave environment.', 'Best Time: Oct-Mar | Entry: ₹65 | Rating: 4.7'),
('Kondaveedu Fort', 'Guntur', 'Andhra Pradesh', 'India', '14th-century hill citadel constructed by Prolaya Vema Reddy.', 'Fort Ramparts, Hill Ponds, Viewpoints', 'Windy hill climate.', 'Best Time: Oct-Mar | Entry: ₹20 | Rating: 4.7'),
('Srisailam Mallikarjuna Temple', 'Srisailam', 'Andhra Pradesh', 'India', 'Holy pilgrimage site in Nallamala Hills housing Mallikarjuna Jyotirlinga.', 'Mallikarjuna Temple, Srisailam Dam, Ropeway', 'Forest hill climate.', 'Best Time: Sep-Mar | Entry: Free | Rating: 4.8'),
('Horsley Hills', 'Madanapalle', 'Andhra Pradesh', 'India', 'Charming hill station famous for eucalyptus groves and cool weather.', 'Sunset Point, Wind Rocks, Zoo', 'Cool year-round.', 'Best Time: Year-Round | Entry: Free | Rating: 4.6'),

('Charminar', 'Hyderabad', 'Telangana', 'India', 'Iconic 16th-century monument featuring four 48.7-meter soaring minarets.', 'Charminar, Laad Bazaar, Mecca Masjid', 'Cool winter nights.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.8'),
('Golconda Fort', 'Hyderabad', 'Telangana', 'India', 'Formidable medieval fortress famous for acoustic architecture and diamond vaults.', 'Fort Ramparts, Acoustic Hall, Qutb Shahi Tombs', 'Sunny hill weather.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.8'),
('Ramoji Film City', 'Hyderabad', 'Telangana', 'India', 'World''s largest film studio complex certified by Guinness.', 'Movie Sets, Stunt Shows, Theme Parks', 'Warm pleasant days.', 'Best Time: Oct-Mar | Entry: ₹1,350 | Rating: 4.7'),
('Yadadri Lakshmi Narasimha Temple', 'Yadadri Bhuvanagiri', 'Telangana', 'India', 'Magnificent cave temple reconstructed with Dravidian black granite architecture.', 'Main Temple Sanctum, Hill Stairs, Gopurams', 'Temple hill climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Warangal Fort', 'Warangal', 'Telangana', 'India', '12th-century fortress featuring carved Kakatiya Toranam archways.', 'Kakatiya Arch, Stone Pillars, Temple Ruins', 'Semi-arid weather.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.7'),
('Ramappa Temple', 'Palampet', 'Telangana', 'India', '13th-century UNESCO World Heritage temple built with floating light bricks.', 'Sandstone Carvings, Floating Bricks, Nandi Mandapam', 'Tropical green surroundings.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Nagarjuna Sagar Dam', 'Nalgonda', 'Telangana', 'India', 'Tallest masonry dam featuring an island Buddhist museum in the reservoir.', 'Masonry Dam, Nagarjunakonda Island Museum, Boating', 'Monsoon reservoir breeze.', 'Best Time: Sep-Feb | Entry: Free | Rating: 4.7'),

('Marina Beach', 'Chennai', 'Tamil Nadu', 'India', 'World''s second-longest natural urban beach stretching 13 km.', 'Beach Promenade, Lighthouse, War Memorial', 'Coastal sea breeze.', 'Best Time: Nov-Feb | Entry: Free | Rating: 4.7'),
('Mahabalipuram Shore Temple', 'Mahabalipuram', 'Tamil Nadu', 'India', 'UNESCO 7th-century rock-cut monuments, Pancha Rathas, and Shore Temple.', 'Shore Temple, Pancha Rathas, Arjuna''s Penance', 'Coastal sea climate.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.8'),
('Ooty Botanical Gardens', 'Ooty', 'Tamil Nadu', 'India', 'Nilgiri hill station famous for tea estates, UNESCO Toy Train, and gardens.', 'Botanical Garden, Ooty Lake, Doddabetta Peak', 'Cool alpine mountain climate.', 'Best Time: Oct-Jun | Entry: ₹30 | Rating: 4.8'),
('Kodaikanal Lake & Pillar Rocks', 'Kodaikanal', 'Tamil Nadu', 'India', 'Princess of Hill Stations set around a star-shaped lake.', 'Kodai Lake, Coaker''s Walk, Pillar Rocks', 'Misty hill resort.', 'Best Time: Sep-May | Entry: Free | Rating: 4.7'),
('Rameswaram Temple & Pamban Bridge', 'Rameswaram', 'Tamil Nadu', 'India', 'Sacred island temple town featuring 1000-pillar corridors and sea bridge.', 'Ramanathaswamy Temple, Pamban Bridge, Dhanushkodi', 'Island coastal climate.', 'Best Time: Oct-Apr | Entry: Free | Rating: 4.8'),
('Meenakshi Amman Temple', 'Madurai', 'Tamil Nadu', 'India', 'Architectural Dravidian temple with 14 colorful gopurams.', '14 Gopurams, Hall of 1000 Pillars, Golden Lotus Tank', 'Temple town climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),

('Munnar Tea Gardens', 'Munnar', 'Kerala', 'India', 'Western Ghats hill station blanketed in emerald green tea plantations.', 'Tea Estates, Eravikulam National Park, Mattupetty Dam', 'Misty cool mountain climate.', 'Best Time: Sep-May | Entry: Free | Rating: 4.8'),
('Alleppey Backwaters & Houseboats', 'Alappuzha', 'Kerala', 'India', 'Venice of the East famous for palm-fringed backwater houseboat cruises.', 'Vembanad Lake, Houseboat Cruises, Marari Beach', 'Tropical backwaters climate.', 'Best Time: Sep-Mar | Entry: ₹5,000 | Rating: 4.9'),
('Fort Kochi & Chinese Fishing Nets', 'Kochi', 'Kerala', 'India', 'Historic spice port town featuring Chinese fishing nets and colonial streets.', 'Chinese Fishing Nets, Mattancherry Palace, Jew Town', 'Coastal marine climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),
('Wayanad Edakkal Caves', 'Wayanad', 'Kerala', 'India', 'Lush hill destination featuring Neolithic cave carvings and waterfalls.', 'Edakkal Caves, Banasura Dam, Chembra Peak', 'Green hill climate.', 'Best Time: Oct-May | Entry: ₹40 | Rating: 4.8'),
('Periyar Wildlife Sanctuary', 'Thekkady', 'Kerala', 'India', 'Protected elephant and tiger reserve surrounding scenic Periyar Lake.', 'Lake Boat Safari, Elephant Junction, Spice Tours', 'Forest mountain climate.', 'Best Time: Oct-Feb | Entry: ₹45 | Rating: 4.7'),
('Kovalam Lighthouse Beach', 'Thiruvananthapuram', 'Kerala', 'India', 'World-famous crescent beach topped by a red-and-white striped lighthouse.', 'Lighthouse Beach, Hawah Beach, Samudra Beach', 'Tropical ocean climate.', 'Best Time: Sep-Mar | Entry: Free | Rating: 4.7'),
('Varkala Cliff Beach', 'Varkala', 'Kerala', 'India', 'Dramatic red laterite cliffs overlooking Arabian Sea waves.', 'Varkala Cliff, Janardanaswamy Temple, Kappil Lake', 'Coastal cliff breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),

('Mysore Palace', 'Mysore', 'Karnataka', 'India', 'Opulent royal residence of Wadiyar Dynasty, famous for Sunday night illuminations.', 'Durbar Hall, Golden Throne, Mysore Zoo', 'Royal city climate.', 'Best Time: Sep-Mar | Entry: ₹100 | Rating: 4.9'),
('Coorg Coffee Estates & Abbey Falls', 'Madikeri', 'Karnataka', 'India', 'Scotland of India famous for coffee plantations and Namdroling Monastery.', 'Abbey Falls, Raja''s Seat, Golden Temple Monastery', 'Cool green hill climate.', 'Best Time: Sep-May | Entry: Free | Rating: 4.8'),
('Hampi Vijayanagara Ruins', 'Hampi', 'Karnataka', 'India', 'UNESCO ruins of Vijayanagara Empire featuring Stone Chariot and Virupaksha Temple.', 'Stone Chariot, Virupaksha Temple, Elephant Stables', 'Bouldered heritage climate.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),
('Gokarna Om Beach', 'Gokarna', 'Karnataka', 'India', 'Serene beach town featuring Om-shaped coastline and Mahabaleshwar Shiva temple.', 'Om Beach, Kudle Beach, Mahabaleshwar Temple', 'Coastal beach climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),
('Jog Falls', 'Shivamogga', 'Karnataka', 'India', 'Second highest plunge waterfall in India dropping 253 meters.', 'Raja Rani Falls, Sharavathi Viewpoint, Hydro Dam', 'Monsoon waterfall mist.', 'Best Time: Aug-Dec | Entry: Free | Rating: 4.8'),
('Chikmagalur Coffee Hills', 'Chikmagalur', 'Karnataka', 'India', 'Birthplace of Indian coffee featuring Mullayanagiri peak.', 'Mullayanagiri, Hebbe Falls, Baba Budangiri', 'Cool hill estate weather.', 'Best Time: Sep-May | Entry: Free | Rating: 4.8'),

('Gateway of India & Marine Drive', 'Mumbai', 'Maharashtra', 'India', 'Iconic basalt arch on Arabian Sea paired with Queen''s Necklace promenade.', 'Gateway Arch, Taj Mahal Palace, Marine Drive', 'Coastal metropolis breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Ajanta Caves', 'Chhatrapati Sambhajinagar', 'Maharashtra', 'India', 'UNESCO 30 rock-cut Buddhist cave monuments featuring ancient frescoes.', 'Buddhist Frescoes, Chaityas, Viharas', 'Shaded rock-cut climate.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),
('Ellora Caves & Kailasa Temple', 'Chhatrapati Sambhajinagar', 'Maharashtra', 'India', 'Largest monolithic rock excavation in the world (Kailasa Temple).', 'Kailasa Temple, Hindu Caves, Jain Caves', 'Basalt cliff environment.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),
('Mahabaleshwar & Venna Lake', 'Mahabaleshwar', 'Maharashtra', 'India', 'Western Ghats hill station famous for strawberry farms and lake boating.', 'Venna Lake, Elephant''s Head Point, Pratapgad Fort', 'Cool hill retreat weather.', 'Best Time: Oct-Jun | Entry: Free | Rating: 4.7'),
('Lonavala & Khandala Ghats', 'Lonavala', 'Maharashtra', 'India', 'Popular hill retreat featuring Bhushi Dam, Karla Caves, and chikki sweet.', 'Bhushi Dam, Tiger''s Leap, Karla Caves', 'Monsoon misty ghats.', 'Best Time: Jul-Feb | Entry: Free | Rating: 4.6'),
('Shirdi Sai Baba Temple', 'Shirdi', 'Maharashtra', 'India', 'Sacred shrine dedicated to 19th-century saint Sai Baba.', 'Main Samadhi Mandir, Dwarkamai, Chavadi', 'Pilgrimage town climate.', 'Best Time: Year-Round | Entry: Free | Rating: 4.9'),

('Jaipur Amber Fort & Hawa Mahal', 'Jaipur', 'Rajasthan', 'India', 'The Pink City featuring hilltop Amer Fort palace and 953-window Hawa Mahal.', 'Amber Fort, Hawa Mahal, City Palace, Jantar Mantar', 'Desert heritage climate.', 'Best Time: Oct-Mar | Entry: ₹100 | Rating: 4.8'),
('Udaipur City Palace & Lake Pichola', 'Udaipur', 'Rajasthan', 'India', 'City of Lakes featuring marble City Palace rising over tranquil Lake Pichola.', 'City Palace, Lake Pichola, Jag Mandir', 'Romantic lake weather.', 'Best Time: Oct-Mar | Entry: ₹300 | Rating: 4.9'),
('Jodhpur Mehrangarh Fort', 'Jodhpur', 'Rajasthan', 'India', 'Imposing Blue City citadel standing 125 meters above the city.', 'Mehrangarh Fort, Jaswant Thada, Umaid Bhawan', 'Desert fort weather.', 'Best Time: Oct-Mar | Entry: ₹100 | Rating: 4.8'),
('Jaisalmer Fort & Thar Desert', 'Jaisalmer', 'Rajasthan', 'India', 'Golden sand-castle fort city in Thar Desert offering camel safaris.', 'Jaisalmer Fort, Sam Sand Dunes, Haveli', 'Desert dunes climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Mount Abu Dilwara Temples', 'Mount Abu', 'Rajasthan', 'India', 'Rajasthan''s only hill station famous for marble Dilwara Jain Temples.', 'Dilwara Temples, Nakki Lake, Sunset Point', 'Cool mountain climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),
('Chittorgarh Fort', 'Chittorgarh', 'Rajasthan', 'India', 'Largest fort complex in India spread across 700 acres.', 'Vijay Stambha, Kirti Stambha, Padmini Palace', 'Historical fort weather.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),

('Baga Beach', 'North Goa', 'Goa', 'India', 'Vibrant beach strip famous for water sports, shacks, and nightlife.', 'Baga Beach, Tito''s Lane, Water Sports', 'Tropical beach sun.', 'Best Time: Oct-Apr | Entry: Free | Rating: 4.7'),
('Calangute Beach', 'North Goa', 'Goa', 'India', 'Queen of Goa Beaches offering expansive golden shores.', 'Calangute Shores, Parasailing, Beach Stalls', 'Sunny beach atmosphere.', 'Best Time: Oct-Apr | Entry: Free | Rating: 4.6'),
('Fort Aguada & Lighthouse', 'Candolim', 'Goa', 'India', '17th-century Portuguese fortress overlooking the Arabian Sea.', 'Aguada Lighthouse, Fort Ramparts, Arabian Sea View', 'Coastal cliff breeze.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.6'),
('Dudhsagar Waterfalls', 'Collem', 'Goa', 'India', 'Four-tiered 310-meter waterfall on Mandovi River in forest sanctuary.', 'Dudhsagar Fall Plunge, Railway Bridge View, Jeep Safari', 'Forest waterfall spray.', 'Best Time: Oct-Feb | Entry: ₹50 | Rating: 4.8'),
('Palolem Beach', 'South Goa', 'Goa', 'India', 'Scenic crescent palm bay in South Goa famous for calm waters.', 'Palolem Bay, Dolphin Boats, Beach Huts', 'Tranquil coastal climate.', 'Best Time: Oct-Apr | Entry: Free | Rating: 4.8'),

('India Gate & Kartavya Path', 'New Delhi', 'Delhi', 'India', '42-meter war memorial arch honoring 84,000 soldiers on Kartavya Path.', 'India Gate, National War Memorial, Rashtrapati Bhavan', 'Capital city weather.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Red Fort (Lal Qila)', 'Old Delhi', 'Delhi', 'India', '17th-century Mughal red sandstone imperial palace fortress.', 'Red Fort Ramparts, Diwan-i-Aam, Diwan-i-Khas', 'Capital heritage weather.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.7'),
('Qutub Minar Complex', 'New Delhi', 'Delhi', 'India', '73-meter brick minaret built in 1192 AD surrounded by ancient ruins.', 'Qutub Minar, Iron Pillar, Alai Darwaza', 'Heritage park setting.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.8'),
('Lotus Temple', 'New Delhi', 'Delhi', 'India', 'Flowerlike white marble lotus-shaped Bahá''í House of Worship.', 'Lotus Sanctum, Ponds, Silent Meditation Hall', 'Peaceful garden climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),
('Humayun''s Tomb', 'New Delhi', 'Delhi', 'India', 'First garden-tomb on Indian subcontinent, precursor to Taj Mahal.', 'Garden Tomb, Barber''s Tomb, Charbagh Gardens', 'Historical garden setting.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.8'),

('Taj Mahal', 'Agra', 'Uttar Pradesh', 'India', 'World Wonder ivory-white marble mausoleum on Yamuna River bank.', 'Taj Mahal, Yamuna View, Inlay Galleries', 'Mughal riverfront weather.', 'Best Time: Oct-Mar | Entry: ₹50 | Rating: 4.9'),
('Agra Fort', 'Agra', 'Uttar Pradesh', 'India', 'Massive red sandstone imperial city fortress of Mughal emperors.', 'Agra Fort Ramparts, Jahangir Palace, Khas Mahal', 'Historical fort climate.', 'Best Time: Oct-Mar | Entry: ₹50 | Rating: 4.8'),
('Fatehpur Sikri', 'Fatehpur Sikri', 'Uttar Pradesh', 'India', '16th-century red sandstone capital city featuring 54m Buland Darwaza.', 'Buland Darwaza, Salim Chishti Tomb, Panch Mahal', 'Semi-arid heritage climate.', 'Best Time: Oct-Mar | Entry: ₹50 | Rating: 4.7'),
('Ayodhya Ram Mandir', 'Ayodhya', 'Uttar Pradesh', 'India', 'Sacred birthplace of Lord Rama featuring the grand Ram Janmabhoomi Mandir.', 'Ram Mandir, Hanuman Garhi, Saryu Ghats', 'Sacred riverfront weather.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Varanasi Ganges Ghats', 'Varanasi', 'Uttar Pradesh', 'India', 'Oldest living city famous for sacred Ganges riverfront ghats and Aarti.', 'Kashi Vishwanath, Dashashwamedh Aarti, Manikarnika', 'Sacred river climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),

('Shimla Mall Road & Ridge', 'Shimla', 'Himachal Pradesh', 'India', 'Colonial summer capital set amidst pine forests.', 'Mall Road, Christ Church, Jakhoo Temple', 'Alpine mountain climate.', 'Best Time: Oct-Jun | Entry: Free | Rating: 4.7'),
('Manali Solang Valley', 'Manali', 'Himachal Pradesh', 'India', 'High-altitude Himalayan retreat featuring adventure sports and Atal Tunnel.', 'Solang Valley, Hadimba Temple, Atal Tunnel', 'Snow mountain climate.', 'Best Time: Oct-Jun | Entry: Free | Rating: 4.8'),
('Dharamshala & McLeod Ganj', 'Dharamshala', 'Himachal Pradesh', 'India', 'Seat of His Holiness Dalai Lama surrounded by Dhauladhar ranges.', 'Tsuglagkhang Monastery, Bhagsunag, Triund', 'Pine mountain climate.', 'Best Time: Sep-Jun | Entry: Free | Rating: 4.8'),
('Spiti Valley Key Monastery', 'Kaza', 'Himachal Pradesh', 'India', 'High-altitude cold mountain desert valley featuring 1000-year-old monastery.', 'Key Monastery, Chandratal Lake, Kibber', 'Cold high desert weather.', 'Best Time: May-Oct | Entry: Free | Rating: 4.9'),

('Rishikesh Laxman Jhula', 'Rishikesh', 'Uttarakhand', 'India', 'Yoga Capital of the World along sacred Ganges River.', 'Laxman Jhula, River Rafting, Triveni Aarti', 'Himalayan river breeze.', 'Best Time: Sep-Jun | Entry: Free | Rating: 4.8'),
('Haridwar Har Ki Pauri', 'Haridwar', 'Uttarakhand', 'India', 'Sacred gateway city on the Ganges famous for evening Ganga Aarti.', 'Har Ki Pauri, Mansa Devi Temple, Chandi Devi', 'Sacred riverfront climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Auli Ski Resort', 'Joshimath', 'Uttarakhand', 'India', 'Premier Himalayan ski resort offering views of Nanda Devi peak.', 'Auli Ropeway, Ski Slopes, Artificial Lake', 'Cold snow mountain weather.', 'Best Time: Dec-Mar | Entry: Free | Rating: 4.8'),
('Nainital Lake', 'Nainital', 'Uttarakhand', 'India', 'Picturesque hill town set around eye-shaped Naini Lake.', 'Naini Lake, Mall Road, Naina Devi Temple', 'Pleasant hill weather.', 'Best Time: Mar-Jun | Entry: Free | Rating: 4.7'),

('Srinagar Dal Lake', 'Srinagar', 'Jammu & Kashmir', 'India', 'Paradise on Earth famous for wooden houseboats and Mughal gardens.', 'Dal Lake Shikara, Shalimar Bagh, Nishat Bagh', 'Alpine valley climate.', 'Best Time: Apr-Oct | Entry: Free | Rating: 4.9'),
('Gulmarg Gondola & Skiing', 'Gulmarg', 'Jammu & Kashmir', 'India', 'Meadow of Flowers featuring world''s highest cable car gondola.', 'Gulmarg Gondola, Apharwat Peak, Ski Slopes', 'Snow alpine climate.', 'Best Time: Dec-Mar | Entry: Free | Rating: 4.9'),
('Pahalgam Betaab Valley', 'Pahalgam', 'Jammu & Kashmir', 'India', 'Valley of Shepherds surrounded by pine forests and Lidder River.', 'Betaab Valley, Aru Valley, Chandanwari', 'Pine mountain breeze.', 'Best Time: Apr-Oct | Entry: Free | Rating: 4.8'),
('Sonamarg Thajiwas Glacier', 'Sonamarg', 'Jammu & Kashmir', 'India', 'Meadow of Gold featuring Sindh River valleys and accessible glacier.', 'Thajiwas Glacier, Zoji La Pass, River Rafting', 'Glacial valley weather.', 'Best Time: Apr-Sep | Entry: Free | Rating: 4.8'),

('Leh Palace & Shanti Stupa', 'Leh', 'Ladakh', 'India', 'High-altitude desert capital featuring 9-storey Leh Palace and Shanti Stupa.', 'Leh Palace, Shanti Stupa, Thiksey Monastery', 'Cold high desert climate.', 'Best Time: May-Sep | Entry: Free | Rating: 4.9'),
('Pangong Tso Lake', 'Leh', 'Ladakh', 'India', 'World''s highest saltwater lake famous for changing color shades.', 'Pangong Lake, Chang La Pass, Spangmik', 'High altitude crisp lake breeze.', 'Best Time: May-Sep | Entry: Free | Rating: 4.9'),
('Nubra Valley Sand Dunes', 'Diskit', 'Ladakh', 'India', 'High-altitude cold desert valley featuring Bactrian camel safaris.', 'Hunder Dunes, Diskit Monastery, Turtuk', 'Desert valley climate.', 'Best Time: May-Sep | Entry: Free | Rating: 4.9'),

('Darjeeling Tiger Hill', 'Darjeeling', 'West Bengal', 'India', 'Queen of Hills famous for Kanchenjunga sunrise views and UNESCO Toy Train.', 'Tiger Hill Sunrise, Toy Train, Batasia Loop', 'Cool Himalayan tea hill.', 'Best Time: Oct-May | Entry: Free | Rating: 4.8'),
('Sundarbans National Park', 'South 24 Parganas', 'West Bengal', 'India', 'World''s largest mangrove forest delta home to Royal Bengal tigers.', 'Mangrove Boat Safari, Sajnekhali Watchtower', 'Estuarine mangrove forest.', 'Best Time: Sep-Mar | Entry: ₹100 | Rating: 4.7'),
('Victoria Memorial Kolkata', 'Kolkata', 'West Bengal', 'India', 'Grand white Makrana marble monument dedicated to Queen Victoria.', 'Victoria Palace, Landscaped Gardens, Museum', 'Metropolitan cultural climate.', 'Best Time: Oct-Mar | Entry: ₹30 | Rating: 4.8'),

('Puri Jagannath Temple', 'Puri', 'Odisha', 'India', 'Sacred Char Dham pilgrimage shrine famous for Ratha Yatra and beach.', 'Jagannath Temple, Puri Golden Beach, Grand Road', 'Coastal pilgrimage breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Konark Sun Temple', 'Konark', 'Odisha', 'India', '13th-century stone architectural wonder designed as a 24-wheeled chariot.', 'Sun Temple Chariot, Chandrabhaga Beach', 'Coastal heritage setting.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),
('Chilika Lake Dolphins', 'Satapada', 'Odisha', 'India', 'Asia''s largest brackish water lagoon famous for Irrawaddy dolphins.', 'Irrawaddy Dolphin Boats, Nalbana Bird Sanctuary', 'Brackish lagoon breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),

('Golden Temple Amritsar', 'Amritsar', 'Punjab', 'India', 'Sacred Sri Harmandir Sahib golden temple with holy Amrit Sarovar.', 'Golden Temple Sanctum, Amrit Sarovar, Langar', 'Serene spiritual climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Wagah Border Ceremony', 'Amritsar', 'Punjab', 'India', 'Thrilling daily military Beating Retreat ceremony at international border.', 'Wagah Border Parade, Border Stadium', 'Patriotic border atmosphere.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),

('Statue of Unity', 'Kevadia', 'Gujarat', 'India', 'World''s tallest 182-meter statue honoring Sardar Vallabhbhai Patel.', '182m Statue Viewing Deck, Sardar Sarovar Dam', 'River valley monument weather.', 'Best Time: Oct-Mar | Entry: ₹150 | Rating: 4.9'),
('Gir National Park', 'Sasan Gir', 'Gujarat', 'India', 'The sole natural habitat of free-roaming Asiatic Lions.', 'Lion Safari, Devalia Park, Gir Forest', 'Dry savanna jungle climate.', 'Best Time: Dec-Mar | Entry: ₹1,000 | Rating: 4.8'),
('Somnath Temple', 'Veraval', 'Gujarat', 'India', 'First among 12 holy Jyotirlinga shrines of Lord Shiva on Arabian Sea coast.', 'Somnath Temple, Sound & Light Show, Sea Ghats', 'Coastal temple breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Dwarkadhish Temple', 'Dwarka', 'Gujarat', 'India', 'Sacred Char Dham temple dedicated to Lord Krishna on Arabian Sea.', 'Dwarkadhish Sanctum, Bet Dwarka Ferry, Nageshwar', 'Coastal sacred breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),

('Khajuraho Monuments', 'Khajuraho', 'Madhya Pradesh', 'India', 'UNESCO World Heritage Nagara-style temples renowned for stone carvings.', 'Kandariya Mahadeva, Lakshmana Temple, Western Group', 'Heritage stone environment.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.9'),
('Sanchi Stupa', 'Sanchi', 'Madhya Pradesh', 'India', 'Oldest stone structure in India commissioned by Emperor Ashoka.', 'Great Stupa, Carved Toranas, Sanchi Museum', 'Peaceful heritage hill.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.8'),
('Pachmarhi Hill Station', 'Pachmarhi', 'Madhya Pradesh', 'India', 'Queen of Satpura hill retreat surrounded by waterfalls and forests.', 'Bee Falls, Dhupgarh Peak, Jata Shankar', 'Cool Satpura forest weather.', 'Best Time: Oct-Jun | Entry: Free | Rating: 4.7'),

('Bodh Gaya Mahabodhi Temple', 'Bodh Gaya', 'Bihar', 'India', 'Sacred site where Lord Buddha attained enlightenment under the Bodhi Tree.', 'Mahabodhi Temple, Sacred Bodhi Tree, Giant Buddha', 'Spiritual peaceful climate.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.9'),
('Nalanda University Ruins', 'Nalanda', 'Bihar', 'India', 'Ruins of ancient world''s premier residential university (5th-12th Century AD).', 'Nalanda Monasteries, Stupas, Museum', 'Historical campus grounds.', 'Best Time: Oct-Mar | Entry: ₹40 | Rating: 4.8'),

('Kaziranga National Park', 'Kanchanjuri', 'Assam', 'India', 'UNESCO World Heritage sanctuary home to two-thirds of world''s one-horned rhinos.', 'One-Horned Rhino Safari, Elephant Patrol, Orchid Park', 'Jungle savanna climate.', 'Best Time: Nov-Apr | Entry: ₹100 | Rating: 4.9'),
('Majuli River Island', 'Majuli', 'Assam', 'India', 'World''s largest river island on Brahmaputra River, famous for Satra monasteries.', 'Kamalabari Satra, Mask Carving Village, Brahmaputra Ferry', 'River island atmosphere.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),

('Shillong & Elephant Falls', 'Shillong', 'Meghalaya', 'India', 'Scotland of the East famous for pine hills, Elephant Falls, and Ward''s Lake.', 'Elephant Falls, Shillong Peak, Ward''s Lake', 'Pine mountain climate.', 'Best Time: Sep-May | Entry: Free | Rating: 4.8'),
('Cherrapunji Living Root Bridges', 'Cherrapunji', 'Meghalaya', 'India', 'Wettest place on earth famous for double-decker living root bridges.', 'Double Decker Root Bridge, Nohkalikai Falls, Mawsmai Cave', 'Misty rainforest weather.', 'Best Time: Oct-May | Entry: ₹40 | Rating: 4.9'),
('Dawki Umngot River', 'Dawki', 'Meghalaya', 'India', 'Famous for crystal clear river waters where boats appear to float in mid-air.', 'Umngot Glass River Boating, Jaflong Point', 'Clear river breeze.', 'Best Time: Nov-Apr | Entry: Free | Rating: 4.9'),

('Gangtok & MG Marg', 'Gangtok', 'Sikkim', 'India', 'Clean mountain capital overlooking Kanchenjunga peak.', 'Rumtek Monastery, MG Marg Promenade, Enchey', 'Cool Himalayan hill weather.', 'Best Time: Mar-May / Oct-Dec | Entry: Free | Rating: 4.8'),
('Tsomgo Glacial Lake', 'Gangtok', 'Sikkim', 'India', 'Sacred glacial lake located at 3,753 meters altitude.', 'Tsomgo Lake, Yak Rides, Nathula Border', 'Alpine glacier weather.', 'Best Time: Mar-May / Oct-Dec | Entry: Free | Rating: 4.9'),

('Tawang Monastery', 'Tawang', 'Arunachal Pradesh', 'India', 'Largest Buddhist monastery in India perched at 3,000 meters altitude.', 'Tawang Monastery, Sela Pass, Madhuri Lake', 'Cold Himalayan mountain air.', 'Best Time: Mar-Oct | Entry: Free | Rating: 4.9'),
('Kohima Kisama Village', 'Kohima', 'Nagaland', 'India', 'Capital of Nagaland famous for Kisama Hornbill Festival and WWII War Cemetery.', 'Kisama Heritage Village, Kohima War Cemetery', 'Cool tribal hill weather.', 'Best Time: Oct-May | Entry: Free | Rating: 4.7'),
('Aizawl & Reiek Peak', 'Aizawl', 'Mizoram', 'India', 'Scenic ridge capital city famous for Reiek Peak and Mizo folk heritage.', 'Reiek Peak, Durtlang Hills, Solomon Temple', 'Cool mountain breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),
('Loktak Lake Floating Park', 'Moirang', 'Manipur', 'India', 'Largest freshwater lake in Northeast featuring floating islands (Phumdis).', 'Keibul Lamjao Park, Sendra Island, Phumdis', 'Lake valley atmosphere.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),
('Ujjayanta Palace Agartala', 'Agartala', 'Tripura', 'India', 'Grand white neoclassical royal palace of Manikya Kings set on twin lakes.', 'Ujjayanta Palace Museum, Neermahal, Heritage Park', 'Royal palace garden climate.', 'Best Time: Oct-Mar | Entry: ₹25 | Rating: 4.7'),
('Chitrakote Falls', 'Jagdalpur', 'Chhattisgarh', 'India', 'Niagara of India dropping 30 meters over horseshoe cliff on Indravati River.', 'Chitrakote Horseshoe Falls, Boat Ride, Indravati River', 'Waterfall mist spray.', 'Best Time: Jul-Mar | Entry: Free | Rating: 4.8'),
('Netarhat Queen of Chotanagpur', 'Latehar', 'Jharkhand', 'India', 'Serene hill town famous for pine forests, sunrise points, and Magnolia Falls.', 'Magnolia Point, Upper Ghaghri, Pine Forests', 'Cool plateau hill air.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.6'),
('Kurukshetra Brahma Sarovar', 'Kurukshetra', 'Haryana', 'India', 'Sacred historic city where Lord Krishna delivered Bhagavad Gita.', 'Brahma Sarovar, Jyotisar Gita Birthplace, Museum', 'Sacred heritage town weather.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.7'),

('Radhanagar Beach Havelock', 'Havelock Island', 'Andaman and Nicobar Islands', 'India', 'Voted Asia''s Best Beach featuring powdery white sand and turquoise waters.', 'Radhanagar White Sand, Sunset Point, Coral Waters', 'Tropical paradise sun.', 'Best Time: Oct-May | Entry: Free | Rating: 4.9'),
('Chandigarh Rock Garden', 'Chandigarh', 'Chandigarh', 'India', 'Sculpture garden created by Nek Chand from industrial and urban waste ceramics.', 'Nek Chand Sculptures, Sukhna Lake, Rose Garden', 'Garden city climate.', 'Best Time: Oct-Mar | Entry: ₹30 | Rating: 4.7'),
('Devka Beach Daman', 'Daman', 'Dadra and Nagar Haveli and Daman and Diu', 'India', 'Relaxing coastal beach promenade featuring musical fountains and Portuguese fort.', 'Devka Promenade, Moti Daman Fort, Jampore', 'Coastal ocean breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.5'),
('Bangaram Island Atoll', 'Bangaram', 'Lakshadweep', 'India', 'Uninhabited coral atoll surrounded by turquoise lagoons and coral reefs.', 'Coral Lagoon, Scuba Diving, Bioluminescent Plankton', 'Pure coral lagoon paradise.', 'Best Time: Oct-May | Entry: Free | Rating: 4.9'),
('Promenade Beach & Auroville', 'Puducherry', 'Puducherry', 'India', 'French Quarter coastal promenade paired with experimental international township Auroville.', 'Promenade Beach, French Quarter, Auroville Matrimandir', 'French coastal breeze.', 'Best Time: Oct-Mar | Entry: Free | Rating: 4.8'),

('Eiffel Tower Paris', 'Paris', 'International', 'France', 'World-famous 330-meter wrought-iron lattice tower on Champ de Mars.', 'Eiffel Tower, Louvre Museum, Seine Cruise', 'European continental climate.', 'Best Time: Jun-Sep | Entry: €26 | Rating: 4.9'),
('Burj Khalifa Dubai', 'Dubai', 'International', 'United Arab Emirates', 'World''s tallest building standing at 828 meters altitude with 163 floors.', 'Burj Khalifa Observation Deck, Dubai Mall, Fountain', 'Desert metropolis sun.', 'Best Time: Nov-Mar | Entry: AED 169 | Rating: 4.9'),
('Marina Bay Sands Singapore', 'Singapore', 'International', 'Singapore', 'Iconic triple-tower resort topped by Sands SkyPark and Gardens by the Bay.', 'Sands SkyPark, Gardens by the Bay, Supertree Grove', 'Tropical city state climate.', 'Best Time: Year-Round | Entry: SGD 26 | Rating: 4.9'),
('Mount Fuji Tokyo', 'Tokyo', 'International', 'Japan', 'Japan''s sacred highest peak (3,776m) reflecting in Fuji Five Lakes.', 'Mount Fuji Peak, Chureito Pagoda, Lake Kawaguchiko', 'Crisp alpine mountain air.', 'Best Time: Jul-Sep | Entry: Free | Rating: 4.9');
